# Copyright (c) 2026 Huawei Technologies Co., Ltd. All Rights Reserved.
# This file is derived from torchtitan,
# https://github.com/pytorch/torchtitan/blob/v0.2.2/tests/integration_tests/run_tests.py
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

import argparse
import logging
import os
import re
import sys
from pathlib import Path
from typing import List  # noqa: PEA001

logger = logging.getLogger(__name__)

sys.path.append(str(Path(__file__).parents[2]))
ROOT = Path(__file__).parents[2]
CUSTOM_TORCHTITAN = ROOT / "third_party" / "torchtitan"
sys.path.insert(0, str(CUSTOM_TORCHTITAN))
import third_party.torchtitan.tests.integration_tests.run_tests as test_module
from third_party.torchtitan.tests.integration_tests import OverrideDefinitions
from third_party.torchtitan.tests.integration_tests.run_tests import _run_cmd, run_tests

original_run_cmd = _run_cmd


def modify_final_cmd(original_cmd):

    # Replace "./run_train.sh" with "bash ./scripts/run_train.sh"
    modified_cmd = original_cmd.replace("./run_train.sh", "bash ./scripts/run_train.sh")

    modified_cmd = re.sub(r"LOG_RANK=[^\s]+", "LOG_RANK=0", modified_cmd)

    dump_match = re.search(r"--job.dump_folder\s+(\S+)", original_cmd)
    if dump_match:
        dump_folder = dump_match.group(1)
        if not os.path.exists(dump_folder):
            os.makedirs(dump_folder)
        log_path = f"{dump_folder}/test.log"
        modified_cmd += f" 2>&1 | tee {log_path}"
    logger.info("Modified command: %s", modified_cmd)
    return modified_cmd


def patched_run_cmd(cmd):
    new_cmd = modify_final_cmd(cmd)
    return original_run_cmd(new_cmd)


ATTR_NAME = "_run_cmd"
setattr(test_module, ATTR_NAME, patched_run_cmd)


def _base_tests() -> List[OverrideDefinitions]:
    return [
        OverrideDefinitions(
            [["--model.name deepseek_v32", "--model.flavor tinymodel"]],
            "DeepSeek V32 BASE",
            "deepseek_v32_base",
            ngpu=2,
        ),
        # Model MTP Test Case for DeepSeek V32
        OverrideDefinitions(
            [
                [
                    "--model.name deepseek_v32",
                    "--model.flavor tinymodel",
                    "--training.num_mtp_modules 1",
                    "--training.mtp_loss_weight 0.3",
                ]
            ],
            "DeepSeek V32 MTP",
            "deepseek_v32_mtp",
            ngpu=2,
        ),
    ]


def _cp_tests() -> List[OverrideDefinitions]:
    return [
        OverrideDefinitions(
            [
                [
                    "--model.name deepseek_v32",
                    "--model.flavor tinymodel",
                    "--model.converters npu_dsa",
                    "--activation_checkpoint.mode full",
                    "--parallelism.context_parallel_degree 2",
                ]
            ],
            "DeepSeek V32 CP DSA",
            "deepseek_v32_cp_dsa",
            ngpu=2,
        ),
        OverrideDefinitions(
            [
                [
                    "--model.name deepseek_v3",
                    "--model.flavor 671B_debug",
                    "--parallelism.context_parallel_degree 2",
                    "--parallelism.enable_custom_context_parallel",
                ]
            ],
            "DeepSeek V3 CP Ulysses",
            "deepseek_v3_cp_ulysses",
            ngpu=2,
        ),
    ]


def _checkpoint_tests() -> List[OverrideDefinitions]:
    return [
        OverrideDefinitions(
            [
                [
                    "--model.name deepseek_v32",
                    "--model.flavor tinymodel",
                    "--training.steps 2",
                    "--checkpoint.enable",
                    "--checkpoint.interval 1",
                    "--checkpoint.folder checkpoint_async_with_pinned_mem",
                    "--checkpoint.async-mode async_with_pinned_mem",
                    "--checkpoint.no-sync-files",
                ]
            ],
            "DeepSeek V32 checkpoint async_with_pinned_mem",
            "deepseek_v32_checkpoint_async_with_pinned_mem",
            ngpu=2,
        ),
    ]


def generate_smoke_tests() -> List[OverrideDefinitions]:
    return _base_tests() + _cp_tests() + _checkpoint_tests()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "output_dir", help="Directory to dump results generated by tests"
    )
    parser.add_argument(
        "--test_suite",
        default="models",
        help="Which test suite to run. If not specified, torchtitan composability tests will be run",
    )
    parser.add_argument(
        "--config_path",
        default="./tests/smoke_tests/base_test.toml",
        help="Base config path for integration tests. This is the config that will be used as a base for all tests.",
    )
    parser.add_argument(
        "--test_name",
        default="all",
        help="Specific test name to run (e.g., 'deepseek_v32_base'). Use 'all' to run all tests.",
    )
    parser.add_argument(
        "--ngpu", default=2, type=int, help="Maximum number of GPUs to use"
    )
    args = parser.parse_args()

    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    test_list = generate_smoke_tests()
    run_tests(args, test_list)


if __name__ == "__main__":
    main()
